import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api, json } from "../../api/client";
import { ErrorAlert, Loading } from "../../components/AsyncState";
import useAuth from "../../hooks/useAuth";

const blankProject = { name: "", startDate: "", endDate: "", description: "", tags: "", version: 1 };
function ValueInput({ item, onChange }) {
  const a = item.attribute; const props = { className: `form-control ${!item.value ? "border-danger" : ""}`, value: item.value, onChange: (e) => onChange(e.target.type === "checkbox" ? String(e.target.checked) : e.target.value) };
  if (a.type === "TEXT") return <textarea rows="4" {...props} />;
  if (a.type === "BOOLEAN") return <div className="form-check form-switch"><input className="form-check-input" type="checkbox" checked={item.value === "true"} onChange={props.onChange} /><label className="form-check-label">{item.value === "true" ? "Yes" : "No"}</label></div>;
  if (a.type === "SELECT") return <select {...props}><option value="">Choose...</option>{a.options.map((x) => <option key={x.id}>{x.label}</option>)}</select>;
  if (a.type === "PERIOD") return <input type="text" placeholder="YYYY-MM-DD / YYYY-MM-DD" {...props} />;
  return <input type={a.type === "NUMERIC" ? "number" : a.type === "DATE" ? "date" : a.type === "IMAGE" ? "url" : "text"} {...props} />;
}

export default function ProfilePage() {
  const { userId } = useParams(); const { setUser } = useAuth(); const [profile, setProfile] = useState(null); const [library, setLibrary] = useState([]); const [tab, setTab] = useState("me"); const [dirtyProfile, setDirtyProfile] = useState(false); const [dirtyValues, setDirtyValues] = useState({}); const [status, setStatus] = useState(""); const [error, setError] = useState(null); const [projectForm, setProjectForm] = useState(null); const saving = useRef(false);
  const load = useCallback(() => Promise.all([api(`/profile${userId ? `?userId=${userId}` : ""}`), api("/attributes")]).then(([p, a]) => { setProfile(p); setLibrary(a); if (!userId) setUser((u) => u ? { ...u, ...p } : u); }).catch(setError), [setUser, userId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    const timer = setInterval(async () => {
      if (saving.current || (!dirtyProfile && !Object.keys(dirtyValues).length)) return;
      saving.current = true; setStatus("Saving changes..."); setError(null);
      try {
        let latest = profile;
        if (dirtyProfile) { const updated = await api("/profile", json("PUT", { ...profile, userId: userId || undefined })); latest = { ...latest, ...updated }; if (!userId) setUser(updated); setDirtyProfile(false); }
        const entries = Object.entries(dirtyValues);
        if (entries.length) {
          const saved = await Promise.all(entries.map(([attributeId, item]) => api(`/profile/attributes/${attributeId}`, json("PUT", { value: item.value, version: item.version, userId: userId || undefined }))));
          const map = new Map(saved.map((x) => [x.attributeId, x])); latest = { ...latest, attributeValues: latest.attributeValues.map((x) => map.get(x.attributeId) || x) }; setDirtyValues({});
        }
        setProfile(latest); setStatus(`Saved at ${new Date().toLocaleTimeString()}`);
      } catch (e) { setError(e); setStatus(e.code === "VERSION_CONFLICT" ? "Conflict detected — reload before editing." : "Save failed"); }
      finally { saving.current = false; }
    }, 6000);
    return () => clearInterval(timer);
  }, [dirtyProfile, dirtyValues, profile, setUser, userId]);
  const profileChange = (key, value) => { setProfile((x) => ({ ...x, [key]: value })); setDirtyProfile(true); setStatus("Unsaved changes"); };
  const valueChange = (attributeId, value) => { setProfile((p) => ({ ...p, attributeValues: p.attributeValues.map((x) => x.attributeId === attributeId ? { ...x, value } : x) })); const item = profile.attributeValues.find((x) => x.attributeId === attributeId); setDirtyValues((x) => ({ ...x, [attributeId]: { ...item, value } })); setStatus("Unsaved changes"); };
  const addAttribute = async (event) => { const id = event.target.value; if (!id) return; try { const item = await api(`/profile/attributes/${id}`, json("PUT", { value: "", version: 0 })); setProfile((x) => ({ ...x, attributeValues: [...x.attributeValues, item] })); } catch (e) { setError(e); } };
  const removeAttribute = async (id) => { try { await api(`/profile/attributes/${id}${userId ? `?userId=${userId}` : ""}`, { method: "DELETE" }); setProfile((x) => ({ ...x, attributeValues: x.attributeValues.filter((a) => a.attributeId !== id) })); } catch (e) { setError(e); } };
  const saveProject = async (event) => { event.preventDefault(); try { const body = { ...projectForm, userId: userId || undefined, tags: projectForm.tags.split(",").map((x) => x.trim()).filter(Boolean) }; await api(projectForm.id ? `/projects/${projectForm.id}` : "/projects", json(projectForm.id ? "PUT" : "POST", body)); setProjectForm(null); load(); } catch (e) { setError(e); } };
  const removeProject = async (id) => { if (!confirm("Remove this project?")) return; try { await api(`/projects/${id}`, { method: "DELETE" }); load(); } catch (e) { setError(e); } };
  if (!profile) return <div className="container"><Loading /></div>;
  const available = library.filter((a) => !a.isBuiltIn && !profile.attributeValues.some((v) => v.attributeId === a.id));
  return <div className="container py-4">{userId && <Link to="/admin/users" className="btn btn-sm btn-outline-secondary mb-3"><i className="bi bi-arrow-left me-2" />Back to users</Link>}<div className="d-flex align-items-center gap-3"><div className="rounded-circle bg-primary-subtle text-primary d-grid" style={{ width: 72, height: 72, placeItems: "center" }}>{profile.photoUrl ? <img className="rounded-circle object-fit-cover" width="72" height="72" src={profile.photoUrl} alt="" /> : <i className="bi bi-person display-5" />}</div><div><h1 className="h2 mb-1">{[profile.firstName, profile.lastName].filter(Boolean).join(" ") || "My profile"}</h1><p className="text-secondary mb-0">{profile.email}{userId && " · Administrator editing mode"}</p></div><div className="ms-auto text-end autosave-status"><span className={`small ${status.includes("failed") || status.includes("Conflict") ? "text-danger" : "text-secondary"}`}>{status || "Changes auto-save every 6 seconds"}</span></div></div><ErrorAlert error={error} />
  <ul className="nav nav-tabs mt-4 mb-4">{[["me", "Me"], ["info", "Info"], ["projects", `Projects (${profile.projects.length})`], ["cvs", `CVs (${profile.cvs.length})`]].map(([key, label]) => <li className="nav-item" key={key}><button className={`nav-link ${tab === key ? "active" : ""}`} onClick={() => setTab(key)}>{label}</button></li>)}</ul>
  {tab === "me" && <div className="card"><div className="card-body"><h2 className="h5">Mandatory profile information</h2><div className="row g-3"><div className="col-md-6"><label className="form-label">First name</label><input className="form-control" value={profile.firstName || ""} onChange={(e) => profileChange("firstName", e.target.value)} /></div><div className="col-md-6"><label className="form-label">Last name</label><input className="form-control" value={profile.lastName || ""} onChange={(e) => profileChange("lastName", e.target.value)} /></div><div className="col-md-6"><label className="form-label">Location</label><input className="form-control" value={profile.location || ""} onChange={(e) => profileChange("location", e.target.value)} /></div><div className="col-md-6"><label className="form-label">External photo URL</label><input type="url" className="form-control" value={profile.photoUrl || ""} onChange={(e) => profileChange("photoUrl", e.target.value)} /><div className="form-text">Images remain in external cloud storage; they are not uploaded to this server.</div></div></div></div></div>}
  {tab === "info" && <><div className="d-flex justify-content-between align-items-end mb-3"><div><h2 className="h4">Reusable information</h2><p className="text-secondary mb-0">Editing here updates every generated CV that uses the attribute.</p></div><select className="form-select w-auto" value="" onChange={addAttribute}><option value="">Add from library...</option>{available.map((a) => <option value={a.id} key={a.id}>{a.name}</option>)}</select></div><div className="row g-3">{profile.attributeValues.map((item) => <div className="col-md-6" key={item.attributeId}><div className="card h-100"><div className="card-body"><div className="d-flex"><label className="form-label fw-semibold me-auto">{item.attribute.name}</label>{!item.attribute.isBuiltIn && <button className="btn btn-sm btn-link text-danger p-0" onClick={() => removeAttribute(item.attributeId)} title="Remove attribute"><i className="bi bi-x-lg" /></button>}</div><ValueInput item={item} onChange={(value) => valueChange(item.attributeId, value)} /><div className="form-text">{item.attribute.description}</div></div></div></div>)}</div></>}
  {tab === "projects" && <><div className="d-flex justify-content-between"><div><h2 className="h4">Projects</h2><p className="text-secondary">Markdown descriptions and reusable autocomplete-friendly tags.</p></div><button className="btn btn-primary align-self-start" onClick={() => setProjectForm(blankProject)}>Add project</button></div>{profile.projects.map((p) => <article className="card mb-3" key={p.id}><div className="card-body"><div className="d-flex"><div className="me-auto"><h3 className="h5">{p.name}</h3><div className="small text-secondary">{p.startDate?.slice(0, 10) || "?"} — {p.endDate?.slice(0, 10) || "Present"}</div></div><div className="dropdown"><button className="btn btn-sm btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown">Actions</button><ul className="dropdown-menu dropdown-menu-end"><li><button className="dropdown-item" onClick={() => setProjectForm({ ...p, startDate: p.startDate?.slice(0, 10) || "", endDate: p.endDate?.slice(0, 10) || "", tags: p.tags.map((x) => x.tag.name).join(", ") })}>Edit</button></li><li><button className="dropdown-item text-danger" onClick={() => removeProject(p.id)}>Delete</button></li></ul></div></div><p className="markdown-preview mt-3">{p.description}</p>{p.tags.map((x) => <span className="badge text-bg-secondary me-1" key={x.tagId}>#{x.tag.name}</span>)}</div></article>)}</>}
  {tab === "cvs" && <div className="table-responsive"><table className="table table-hover"><thead><tr><th>Position</th><th>Status</th><th>Updated</th><th className="text-end">Likes</th></tr></thead><tbody>{profile.cvs.map((cv) => <tr key={cv.id}><td><Link to={`/cvs/${cv.id}`}>{cv.position.title}</Link></td><td><span className={`badge text-bg-${cv.status === "PUBLISHED" ? "success" : "secondary"}`}>{cv.status}</span></td><td>{new Date(cv.updatedAt).toLocaleDateString()}</td><td className="text-end">{cv._count.likes}</td></tr>)}</tbody></table></div>}
  {projectForm && <div className="modal d-block" style={{ background: "rgba(0,0,0,.45)" }}><div className="modal-dialog modal-lg"><form className="modal-content" onSubmit={saveProject}><div className="modal-header"><h2 className="h5 modal-title">{projectForm.id ? "Edit" : "Add"} project</h2><button type="button" className="btn-close" onClick={() => setProjectForm(null)} /></div><div className="modal-body"><div className="row g-3"><div className="col-12"><label className="form-label">Name</label><input required className="form-control" value={projectForm.name} onChange={(e) => setProjectForm({ ...projectForm, name: e.target.value })} /></div><div className="col-md-6"><label className="form-label">Start date</label><input type="date" className="form-control" value={projectForm.startDate} onChange={(e) => setProjectForm({ ...projectForm, startDate: e.target.value })} /></div><div className="col-md-6"><label className="form-label">End date</label><input type="date" className="form-control" value={projectForm.endDate} onChange={(e) => setProjectForm({ ...projectForm, endDate: e.target.value })} /></div><div className="col-12"><label className="form-label">Description (Markdown)</label><textarea rows="5" className="form-control" value={projectForm.description} onChange={(e) => setProjectForm({ ...projectForm, description: e.target.value })} /></div><div className="col-12"><label className="form-label">Technology tags</label><input className="form-control" list="known-tags" placeholder="react, node.js, sql" value={projectForm.tags} onChange={(e) => setProjectForm({ ...projectForm, tags: e.target.value })} /></div></div></div><div className="modal-footer"><button type="button" className="btn btn-outline-secondary" onClick={() => setProjectForm(null)}>Cancel</button><button className="btn btn-primary">Save project</button></div></form></div></div>}
  </div>;
}
