import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api, json } from "../../api/client";
import { ErrorAlert, Loading } from "../../components/AsyncState";
import useAuth from "../../hooks/useAuth";

function EditableValue({ item, canEdit, onSave }) {
  const [value, setValue] = useState(item.value); const missing = item.required && !value;
  if (!canEdit || item.attribute.isBuiltIn) return <div className={`p-3 rounded ${missing ? "missing-value" : ""}`}><strong>{item.attribute.name}</strong><div className="markdown-preview mt-1">{value || "Missing information"}</div></div>;
  const save = () => value !== item.value && onSave(item, value);
  const input = item.attribute.type === "TEXT" ? <textarea className={`form-control ${missing ? "is-invalid" : ""}`} rows="4" value={value} onChange={(e) => setValue(e.target.value)} onBlur={save} /> : item.attribute.type === "BOOLEAN" ? <div className="form-check form-switch"><input type="checkbox" className="form-check-input" checked={value === "true"} onChange={(e) => { const next = String(e.target.checked); setValue(next); onSave(item, next); }} /></div> : item.attribute.type === "SELECT" ? <select className={`form-select ${missing ? "is-invalid" : ""}`} value={value} onChange={(e) => { setValue(e.target.value); onSave(item, e.target.value); }}><option value="">Choose...</option>{item.attribute.options.map((x) => <option key={x.id}>{x.label}</option>)}</select> : <input className={`form-control ${missing ? "is-invalid" : ""}`} type={item.attribute.type === "NUMERIC" ? "number" : item.attribute.type === "DATE" ? "date" : "text"} value={value} onChange={(e) => setValue(e.target.value)} onBlur={save} />;
  return <div className={`p-3 rounded ${missing ? "missing-value" : ""}`}><label className="form-label fw-semibold">{item.attribute.name}</label>{input}{missing && <div className="invalid-feedback d-block">Required before publishing</div>}</div>;
}

export default function CvDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const [cv, setCv] = useState(null); const [error, setError] = useState(null); const [message, setMessage] = useState(""); const recruiter = user.roles.includes("RECRUITER") || user.roles.includes("ADMIN");
  const load = useCallback(() => { api(`/cvs/${id}`).then(setCv).catch(setError); }, [id]);
  useEffect(() => { load(); }, [load]);
  const saveValue = async (item, value) => { try { await api(`/profile/attributes/${item.attribute.id}`, json("PUT", { value, version: item.version, userId: cv.userId })); setMessage("Profile value saved. Every linked CV now uses it."); load(); } catch (e) { setError(e); } };
  const publish = async () => { try { const updated = await api(`/cvs/${id}/publish`, { method: "POST" }); setCv(updated); setMessage("CV published and visible to recruiters."); } catch (e) { setError(e); } };
  const like = async () => { try { const result = await api(`/cvs/${id}/like`, { method: "POST" }); setCv({ ...cv, likedByMe: result.liked, likeCount: result.count }); } catch (e) { setError(e); } };
  if (!cv) return <div className="container"><Loading /></div>;
  const complete = cv.values.every((x) => !x.required || x.value);
  return <div className="container py-4"><div className="no-print d-flex flex-wrap gap-2 mb-3"><Link className="btn btn-outline-secondary" to="/cvs"><i className="bi bi-arrow-left me-2" />All CVs</Link><button className="btn btn-outline-secondary" onClick={() => window.print()}><i className="bi bi-printer me-2" />Print / Save PDF</button>{cv.canEdit && cv.status !== "PUBLISHED" && <button className="btn btn-success" disabled={!complete} onClick={publish}><i className="bi bi-send-check me-2" />Publish CV</button>}{recruiter && cv.status === "PUBLISHED" && <button className={`btn btn-${cv.likedByMe ? "primary" : "outline-primary"}`} onClick={like}><i className={`bi bi-heart${cv.likedByMe ? "-fill" : ""} me-2`} />{cv.likeCount}</button>}<span className={`badge text-bg-${cv.status === "PUBLISHED" ? "success" : "secondary"} align-self-center`}>{cv.status}</span></div><ErrorAlert error={error} />{message && <div className="alert alert-success no-print">{message}</div>}
  <article className="cv-sheet p-4 p-md-5"><header className="border-bottom pb-4 mb-4"><div className="d-flex justify-content-between gap-4"><div><p className="text-primary fw-semibold text-uppercase mb-2">Curriculum Vitae</p><h1 className="display-5 fw-bold">{[cv.user.firstName, cv.user.lastName].filter(Boolean).join(" ") || "Candidate"}</h1><p className="lead mb-1">{cv.position.title}</p><p className="text-secondary mb-0">{cv.user.location || "Location not provided"}</p></div>{cv.user.photoUrl && <img src={cv.user.photoUrl} alt="Candidate" width="120" height="120" className="rounded object-fit-cover" />}</div></header>
  <section className="mb-5"><h2 className="h4 text-primary border-bottom pb-2">Professional information</h2><div className="row g-3">{cv.values.filter((x) => !["First Name", "Last Name", "Location", "Personal Photo"].includes(x.attribute.name)).map((item) => <div className={item.attribute.type === "TEXT" ? "col-12" : "col-md-6"} key={item.attribute.id}><EditableValue item={item} canEdit={cv.canEdit} onSave={saveValue} /></div>)}</div></section>
  {cv.projects.length > 0 && <section><h2 className="h4 text-primary border-bottom pb-2">Selected projects</h2>{cv.projects.map(({ project }) => <article className="mb-4" key={project.id}><div className="d-flex justify-content-between"><h3 className="h5">{project.name}</h3><span className="small text-secondary">{project.startDate?.slice(0, 10)} — {project.endDate?.slice(0, 10) || "Present"}</span></div><p className="markdown-preview">{project.description}</p>{project.tags.map((x) => <span className="badge text-bg-secondary me-1" key={x.tagId}>{x.tag.name}</span>)}</article>)}</section>}
  <footer className="border-top pt-3 mt-5 text-secondary small">Generated for {cv.position.title} at {cv.position.company || "the recruiting organization"}. This CV reads live values from the candidate's reusable profile.</footer></article></div>;
}
