import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../../api/client";
import { Empty, ErrorAlert, Loading } from "../../components/AsyncState";
import useAuth from "../../hooks/useAuth";

export default function CvListPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [rows, setRows] = useState(null); const [selected, setSelected] = useState([]); const [error, setError] = useState(null); const staff = user.roles.some((r) => ["RECRUITER", "ADMIN"].includes(r));
  const load = useCallback(() => { api("/cvs").then(setRows).catch(setError); }, []);
  useEffect(() => { load(); }, [load]);
  const remove = async () => { if (!confirm(`Delete ${selected.length} CV(s)?`)) return; try { await Promise.all(selected.map((id) => api(`/cvs/${id}`, { method: "DELETE" }))); setSelected([]); load(); } catch (e) { setError(e); } };
  return <div className="container py-4"><div className="d-flex justify-content-between"><div><h1 className="h2">{staff ? "Published candidate CVs" : "My CVs"}</h1><p className="text-secondary">{staff ? "Browse the shared candidate pool." : "One live, profile-linked CV per position."}</p></div>{!staff && <Link className="btn btn-primary align-self-start" to="/positions">Create from a position</Link>}</div><ErrorAlert error={error} />{selected.length > 0 && <div className="toolbar alert alert-primary d-flex gap-2"><strong className="me-auto">{selected.length} selected</strong><button className="btn btn-sm btn-primary" disabled={selected.length !== 1} onClick={() => navigate(`/cvs/${selected[0]}`)}>Open</button>{!staff && <button className="btn btn-sm btn-danger" onClick={remove}>Delete</button>}<button className="btn-close" onClick={() => setSelected([])} /></div>}
  {!rows ? <Loading /> : rows.length === 0 ? <Empty icon="file-earmark-person">No CVs found.</Empty> : <div className="table-responsive"><table className="table table-hover table-select align-middle"><thead><tr><th></th>{staff && <th>Candidate</th>}<th>Position</th><th>Company</th><th>Status</th><th>Updated</th><th className="text-end">Likes</th></tr></thead><tbody>{rows.map((cv) => <tr key={cv.id} className={selected.includes(cv.id) ? "selected" : ""} onClick={() => setSelected(selected.includes(cv.id) ? [] : [cv.id])} onDoubleClick={() => navigate(`/cvs/${cv.id}`)}><td><input type="checkbox" checked={selected.includes(cv.id)} readOnly /></td>{staff && <td>{[cv.user.firstName, cv.user.lastName].filter(Boolean).join(" ") || cv.user.email}</td>}<td><button className="btn btn-link p-0 text-decoration-none fw-semibold" onClick={(e) => { e.stopPropagation(); navigate(`/cvs/${cv.id}`); }}>{cv.position.title}</button></td><td>{cv.position.company || "—"}</td><td><span className={`badge text-bg-${cv.status === "PUBLISHED" ? "success" : "secondary"}`}>{cv.status}</span></td><td>{new Date(cv.updatedAt).toLocaleDateString()}</td><td className="text-end">{cv._count.likes}</td></tr>)}</tbody></table><p className="small text-secondary">Select rows to reveal actions. Double-click to open.</p></div>}</div>;
}
