import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { ErrorAlert, Loading } from "../components/AsyncState";
import useAuth from "../hooks/useAuth";

export default function HomePage() {
  const { user } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState(null);
  useEffect(() => { api("/dashboard").then(setData).catch(setError); }, []);
  return <><section className="hero border-bottom"><div className="container py-5 py-lg-6"><div className="row align-items-center g-5"><div className="col-lg-7"><span className="badge text-bg-primary mb-3">Recruitment, organized</span><h1 className="display-4 fw-bold">One professional profile. A tailored CV for every position.</h1><p className="lead text-secondary">Candidates keep reusable career data, recruiters design flexible position templates, and CV Forge assembles the right information automatically.</p><div className="d-flex gap-2"><Link className="btn btn-primary btn-lg" to="/positions">Browse positions</Link><Link className="btn btn-outline-primary btn-lg" to={user ? "/profile" : "/login"}>{user ? "Open profile" : "Get started"}</Link></div></div><div className="col-lg-5"><div className="p-4 bg-body rounded-4 border shadow-sm"><h2 className="h4">How it works</h2>{["Build your reusable professional profile", "Choose an accessible position", "Review, complete, and publish the generated CV"].map((x, i) => <div className="d-flex gap-3 py-3 border-bottom" key={x}><span className="badge rounded-pill text-bg-primary align-self-start">{i + 1}</span><span>{x}</span></div>)}</div></div></div></div></section>
    <div className="container py-5"><ErrorAlert error={error} />{!data ? <Loading /> : <><section className="row g-3 mb-5">{Object.entries({ positions: "Positions", candidates: "Candidates", recruiters: "Recruiters", submitted: "Published CVs", recentCvs: "CVs in 24 hours" }).map(([key, label]) => <div className="col-6 col-lg" key={key}><div className="metric p-3 border rounded h-100"><div className="h3 mb-0">{data.stats[key]}</div><small className="text-secondary">{label}</small></div></div>)}</section>
      <div className="row g-5"><section className="col-lg-7"><div className="d-flex justify-content-between align-items-center"><h2 className="h3">Latest positions</h2><Link to="/positions">View all</Link></div><div className="table-responsive"><table className="table table-hover align-middle"><thead><tr><th>Position</th><th>Company</th><th>Level</th><th className="text-end">CVs</th></tr></thead><tbody>{data.latest.map((p) => <tr key={p.id} onClick={() => location.assign(`/positions/${p.id}`)} role="link"><td><Link to={`/positions/${p.id}`} className="fw-semibold text-decoration-none">{p.title}</Link></td><td>{p.company || "—"}</td><td>{p.level?.replace("_", "-") || "—"}</td><td className="text-end">{p._count.cvs}</td></tr>)}</tbody></table></div></section>
      <section className="col-lg-5"><h2 className="h3">Most popular</h2><ol className="list-group list-group-numbered mb-4">{data.popular.map((p) => <li className="list-group-item d-flex justify-content-between" key={p.id}><Link to={`/positions/${p.id}`} className="text-decoration-none">{p.title}</Link><span className="badge text-bg-primary rounded-pill">{p._count.cvs}</span></li>)}</ol><h2 className="h4">Technology tags</h2><div className="tag-cloud">{data.tags.map((x) => <Link key={x.id} to={`/search?q=${encodeURIComponent(x.name)}`} style={{ fontSize: `${.85 + Math.min(1, (x._count.projects + x._count.positions) * .12)}rem` }}>#{x.name}</Link>)}</div></section></div></>}</div></>;
}
