import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { Empty, ErrorAlert, Loading } from "../components/AsyncState";

export default function SearchPage() {
  const [params] = useSearchParams(); const q = params.get("q") || ""; const [data, setData] = useState(null); const [error, setError] = useState(null);
  useEffect(() => { setData(null); api(`/search?q=${encodeURIComponent(q)}`).then(setData).catch(setError); }, [q]);
  return <div className="container py-4"><h1 className="h2">Search results</h1><p className="text-secondary">Matches for <strong>“{q}”</strong> across accessible positions, published CVs, and public candidate identities.</p><ErrorAlert error={error} />{!data ? <Loading /> : data.positions.length + data.cvs.length + data.users.length === 0 ? <Empty icon="search">No matching results.</Empty> : <div className="row g-4"><section className="col-lg-7"><h2 className="h4">Positions ({data.positions.length})</h2><div className="table-responsive"><table className="table table-hover"><thead><tr><th>Title</th><th>Company</th><th>Level</th></tr></thead><tbody>{data.positions.map((p) => <tr key={p.id}><td><Link to={`/positions/${p.id}`}>{p.title}</Link></td><td>{p.company}</td><td>{p.level?.replace("_", "-") || "—"}</td></tr>)}</tbody></table></div><h2 className="h4 mt-4">Published CVs ({data.cvs.length})</h2><div className="table-responsive"><table className="table table-hover"><thead><tr><th>Candidate</th><th>Position</th><th>Likes</th></tr></thead><tbody>{data.cvs.map((cv) => <tr key={cv.id}><td><Link to={`/cvs/${cv.id}`}>{[cv.user.firstName, cv.user.lastName].filter(Boolean).join(" ")}</Link></td><td>{cv.position.title}</td><td>{cv._count.likes}</td></tr>)}</tbody></table></div></section><aside className="col-lg-5"><h2 className="h4">People ({data.users.length})</h2><div className="list-group">{data.users.map((u) => <Link className="list-group-item list-group-item-action" to={`/public-profile/${u.id}`} key={u.id}><i className="bi bi-person-circle me-2" />{[u.firstName, u.lastName].filter(Boolean).join(" ") || "Candidate"}</Link>)}</div></aside></div>}</div>;
}
