import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, json } from "../../api/client";
import { ErrorAlert, Loading } from "../../components/AsyncState";

export default function UserManagementPage() {
  const [rows, setRows] = useState(null); const [selected, setSelected] = useState([]); const [role, setRole] = useState("RECRUITER"); const [error, setError] = useState(null);
  const load = useCallback(() => { api("/users").then(setRows).catch(setError); }, []);
  useEffect(() => { load(); }, [load]);
  const action = async (name) => { if (name === "delete" && !confirm("Delete selected user accounts? This cannot be undone.")) return; try { await api("/users/bulk", json("PATCH", { ids: selected, action: name, role })); setSelected([]); load(); } catch (e) { setError(e); } };
  return <div className="container py-4"><h1 className="h2">User Management</h1><p className="text-secondary">Select users, then use the shared toolbar. No repetitive row action buttons.</p><ErrorAlert error={error} />{selected.length > 0 && <div className="toolbar alert alert-primary d-flex flex-wrap gap-2 align-items-center"><strong className="me-auto">{selected.length} selected</strong><button className="btn btn-sm btn-warning" onClick={() => action("block")}>Block</button><button className="btn btn-sm btn-success" onClick={() => action("unblock")}>Unblock</button><select className="form-select form-select-sm w-auto" value={role} onChange={(e) => setRole(e.target.value)}>{["CANDIDATE", "RECRUITER", "ADMIN"].map((x) => <option key={x}>{x}</option>)}</select><button className="btn btn-sm btn-primary" onClick={() => action("addRole")}>Assign role</button><button className="btn btn-sm btn-outline-primary" onClick={() => action("removeRole")}>Remove role</button><button className="btn btn-sm btn-danger" onClick={() => action("delete")}>Delete</button><button className="btn-close" onClick={() => setSelected([])} /></div>}
  {!rows ? <Loading /> : <div className="table-responsive"><table className="table table-hover table-select align-middle"><thead><tr><th><input type="checkbox" checked={selected.length === rows.length} onChange={() => setSelected(selected.length === rows.length ? [] : rows.map((x) => x.id))} /></th><th>User</th><th>Email</th><th>Roles</th><th>Status</th><th>Language</th><th>Theme</th></tr></thead><tbody>{rows.map((u) => <tr key={u.id} className={selected.includes(u.id) ? "selected" : ""} onClick={() => setSelected((old) => old.includes(u.id) ? old.filter((x) => x !== u.id) : [...old, u.id])}><td><input type="checkbox" checked={selected.includes(u.id)} readOnly /></td><td><Link to={`/admin/users/${u.id}/profile`} onClick={(event) => event.stopPropagation()}>{[u.firstName, u.lastName].filter(Boolean).join(" ") || "Open profile"}</Link></td><td>{u.email}</td><td>{u.roles.map((r) => <span className="badge text-bg-primary me-1" key={r}>{r}</span>)}</td><td><span className={`badge text-bg-${u.isBlocked ? "danger" : "success"}`}>{u.isBlocked ? "Blocked" : "Active"}</span></td><td>{u.preferredLanguage}</td><td>{u.preferredTheme}</td></tr>)}</tbody></table></div>}</div>;
}
