import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api, json } from "../../api/client";
import { ErrorAlert, Loading } from "../../components/AsyncState";

const blank = { title: "", company: "", level: "", description: "", isPublic: true, maxProjects: 3, attributeIds: [], accessRules: [], tags: "", version: 1 };
const operators = (type) => type === "BOOLEAN" ? ["IS_TRUE", "IS_FALSE"] : type === "NUMERIC" || type === "DATE" ? ["EQUALS", "GREATER_THAN", "GREATER_OR_EQUAL", "LESS_THAN", "LESS_OR_EQUAL"] : ["EQUALS", "NOT_EQUALS", "CONTAINS"];
export default function PositionEditorPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(blank); const [attributes, setAttributes] = useState(null); const [error, setError] = useState(null); const editing = Boolean(id);
  useEffect(() => { Promise.all([api("/attributes"), editing ? api(`/positions/${id}`) : null]).then(([items, position]) => { setAttributes(items); if (position) setForm({ ...position, attributeIds: position.attributes.map((x) => x.attributeId), accessRules: position.accessRules.map((x) => ({ attributeId: x.attributeId, operator: x.operator, expected: x.expected })), tags: position.tags.map((x) => x.tag.name).join(", ") }); }).catch(setError); }, [id, editing]);
  const selectedAttributes = useMemo(() => attributes?.filter((x) => form.attributeIds.includes(x.id)) || [], [attributes, form.attributeIds]);
  const toggle = (attributeId) => setForm((x) => ({ ...x, attributeIds: x.attributeIds.includes(attributeId) ? x.attributeIds.filter((a) => a !== attributeId) : [...x.attributeIds, attributeId] }));
  const addRule = () => { const a = selectedAttributes[0]; if (a) setForm((x) => ({ ...x, isPublic: false, accessRules: [...x.accessRules, { attributeId: a.id, operator: operators(a.type)[0], expected: "" }] })); };
  const save = async (event) => { event.preventDefault(); setError(null); try { const payload = { ...form, level: form.level || null, tags: form.tags.split(",").map((x) => x.trim()).filter(Boolean) }; const result = await api(editing ? `/positions/${id}` : "/positions", json(editing ? "PUT" : "POST", payload)); navigate(`/positions/${result.id}`); } catch (e) { setError(e); } };
  if (!attributes) return <div className="container"><Loading /></div>;
  return <div className="container py-4"><h1 className="h2">{editing ? "Edit position" : "Create position"}</h1><ErrorAlert error={error} /><form onSubmit={save}><div className="row g-4"><div className="col-lg-7"><section className="card mb-4"><div className="card-body"><h2 className="h5">Basic information</h2><div className="row g-3"><div className="col-md-7"><label className="form-label">Title</label><input required className="form-control" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></div><div className="col-md-5"><label className="form-label">Company</label><input className="form-control" value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></div><div className="col-md-6"><label className="form-label">Level</label><select className="form-select" value={form.level || ""} onChange={(e) => setForm({ ...form, level: e.target.value })}><option value="">Not specified</option>{["JUNIOR", "MIDDLE", "SENIOR", "C_LEVEL"].map((x) => <option key={x}>{x}</option>)}</select></div><div className="col-md-6"><label className="form-label">Maximum projects</label><input type="number" min="0" max="10" className="form-control" value={form.maxProjects} onChange={(e) => setForm({ ...form, maxProjects: e.target.value })} /></div><div className="col-12"><label className="form-label">Short description</label><textarea className="form-control" rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="col-12"><label className="form-label">Relevant technology tags <span className="text-secondary">(comma-separated)</span></label><input className="form-control" value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} /></div></div></div></section>
      <section className="card"><div className="card-body"><div className="d-flex justify-content-between"><h2 className="h5">Access rules</h2><div className="form-check form-switch"><input className="form-check-input" type="checkbox" checked={form.isPublic} onChange={(e) => setForm({ ...form, isPublic: e.target.checked, accessRules: e.target.checked ? [] : form.accessRules })} /><label className="form-check-label">Public</label></div></div>{!form.isPublic && <><p className="small text-secondary">A candidate must satisfy every rule.</p>{form.accessRules.map((r, i) => { const a = attributes.find((x) => x.id === r.attributeId); return <div className="row g-2 mb-2" key={i}><div className="col-md-5"><select className="form-select" value={r.attributeId} onChange={(e) => { const copy = [...form.accessRules]; copy[i] = { attributeId: e.target.value, operator: operators(attributes.find((x) => x.id === e.target.value)?.type)[0], expected: "" }; setForm({ ...form, accessRules: copy }); }}>{selectedAttributes.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></div><div className="col-md-3"><select className="form-select" value={r.operator} onChange={(e) => { const copy = [...form.accessRules]; copy[i].operator = e.target.value; setForm({ ...form, accessRules: copy }); }}>{operators(a?.type).map((x) => <option key={x}>{x}</option>)}</select></div><div className="col"><input className="form-control" disabled={r.operator.startsWith("IS_")} value={r.expected} onChange={(e) => { const copy = [...form.accessRules]; copy[i].expected = e.target.value; setForm({ ...form, accessRules: copy }); }} /></div><div className="col-auto"><button type="button" className="btn btn-outline-danger" onClick={() => setForm({ ...form, accessRules: form.accessRules.filter((_, n) => n !== i) })}><i className="bi bi-x-lg" /></button></div></div>; })}<button type="button" className="btn btn-sm btn-outline-primary" disabled={!selectedAttributes.length} onClick={addRule}>Add rule</button></>}</div></section></div>
      <div className="col-lg-5"><section className="card"><div className="card-body"><h2 className="h5">CV template attributes</h2><p className="small text-secondary">Choose reusable fields to appear in generated CVs.</p><div className="list-group overflow-auto" style={{ maxHeight: 520 }}>{attributes.map((a) => <label className="list-group-item" key={a.id}><input className="form-check-input me-2" type="checkbox" checked={form.attributeIds.includes(a.id)} onChange={() => toggle(a.id)} /><strong>{a.name}</strong><div className="small text-secondary ms-4">{a.category.replaceAll("_", " ")} · {a.type}</div></label>)}</div></div></section></div></div><div className="d-flex gap-2 mt-4"><button className="btn btn-primary" type="submit">Save position</button><button className="btn btn-outline-secondary" type="button" onClick={() => navigate(-1)}>Cancel</button></div></form></div>;
}
