import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, json } from "../../api/client";
import { ErrorAlert, Loading } from "../../components/AsyncState";
import useAuth from "../../hooks/useAuth";

function Discussion({ positionId }) {
  const [posts, setPosts] = useState([]); const [content, setContent] = useState(""); const [error, setError] = useState(null);
  const load = useCallback(() => api(`/positions/${positionId}/posts`).then(setPosts).catch(setError), [positionId]);
  useEffect(() => { load(); const timer = setInterval(load, 3000); return () => clearInterval(timer); }, [load]);
  const submit = async (event) => { event.preventDefault(); try { await api(`/positions/${positionId}/posts`, json("POST", { content })); setContent(""); load(); } catch (e) { setError(e); } };
  return <><ErrorAlert error={error} /><div className="discussion list-group mb-3">{posts.map((post) => <article className="list-group-item" key={post.id}><div className="d-flex justify-content-between"><Link className="fw-semibold text-decoration-none" to={`/public-profile/${post.author.id}`}>{[post.author.firstName, post.author.lastName].filter(Boolean).join(" ") || "User"}</Link><time className="small text-secondary">{new Date(post.createdAt).toLocaleString()}</time></div><div className="markdown-preview mt-2">{post.content}</div></article>)}</div><form onSubmit={submit}><label className="form-label">Add to the discussion <span className="text-secondary">(Markdown supported)</span></label><textarea required className="form-control" rows="3" value={content} onChange={(e) => setContent(e.target.value)} /><button className="btn btn-primary mt-2">Post</button></form></>;
}

export default function PositionDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [position, setPosition] = useState(null); const [cvs, setCvs] = useState([]); const [error, setError] = useState(null); const [tab, setTab] = useState("overview");
  const staff = user?.roles.some((r) => ["RECRUITER", "ADMIN"].includes(r)); const candidate = user?.roles.some((r) => ["CANDIDATE", "ADMIN"].includes(r));
  useEffect(() => { api(`/positions/${id}`).then(setPosition).catch(setError); if (staff) api(`/cvs?positionId=${id}`).then(setCvs).catch(() => {}); }, [id, staff]);
  const createCv = async () => { try { const cv = await api("/cvs", json("POST", { positionId: id })); navigate(`/cvs/${cv.id}`); } catch (e) { if (e.status === 409) navigate("/cvs"); else setError(e); } };
  if (!position && !error) return <div className="container"><Loading /></div>;
  return <div className="container py-4"><ErrorAlert error={error} />{position && <><nav aria-label="breadcrumb"><ol className="breadcrumb"><li className="breadcrumb-item"><Link to="/positions">Positions</Link></li><li className="breadcrumb-item active">{position.title}</li></ol></nav><div className="d-flex flex-wrap justify-content-between gap-3"><div><div className="d-flex gap-2 align-items-center"><h1 className="display-6 fw-bold mb-1">{position.title}</h1><span className={`badge text-bg-${position.isPublic ? "success" : "warning"}`}>{position.isPublic ? "Public" : "Restricted"}</span></div><p className="lead text-secondary">{position.company}{position.level ? ` · ${position.level.replace("_", "-")}` : ""}</p></div><div className="no-print d-flex gap-2 align-self-start">{staff && <button className="btn btn-outline-primary" onClick={() => navigate(`/positions/${id}/edit`)}>Edit template</button>}{candidate && <button className="btn btn-primary" onClick={createCv}><i className="bi bi-file-earmark-plus me-2" />Create my CV</button>}</div></div>
    <ul className="nav nav-tabs mt-3 mb-4">{["overview", "discussion", ...(staff ? ["candidates"] : [])].map((x) => <li className="nav-item" key={x}><button className={`nav-link ${tab === x ? "active" : ""}`} onClick={() => setTab(x)}>{x[0].toUpperCase() + x.slice(1)}{x === "discussion" && ` (${position._count.posts})`}</button></li>)}</ul>
    {tab === "overview" && <div className="row g-4"><div className="col-lg-8"><section className="card mb-4"><div className="card-body"><h2 className="h4">About this position</h2><p className="markdown-preview">{position.description || "No description provided."}</p><div>{position.tags.map((x) => <span className="badge text-bg-secondary me-1" key={x.tagId}>#{x.tag.name}</span>)}</div></div></section><section className="card"><div className="card-body"><h2 className="h4">CV template</h2><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Attribute</th><th>Category</th><th>Type</th></tr></thead><tbody>{position.attributes.map((x) => <tr key={x.attributeId}><td>{x.attribute.name}</td><td>{x.attribute.category.replaceAll("_", " ")}</td><td>{x.attribute.type}</td></tr>)}</tbody></table></div></div></section></div><aside className="col-lg-4"><div className="card"><div className="card-body"><h2 className="h5">Template details</h2><dl><dt>Maximum projects</dt><dd>{position.maxProjects}</dd><dt>Generated CVs</dt><dd>{position._count.cvs}</dd><dt>Access rules</dt><dd>{position.isPublic ? "All authenticated candidates" : `${position.accessRules.length} profile condition(s)`}</dd></dl>{!position.isPublic && position.accessRules.map((r) => <div className="small border-top pt-2" key={r.id}>{r.attribute.name} <strong>{r.operator.replaceAll("_", " ")}</strong> {r.expected}</div>)}</div></div></aside></div>}
    {tab === "discussion" && (user ? <Discussion positionId={id} /> : <div className="alert alert-info">Sign in to join the discussion.</div>)}
    {tab === "candidates" && <div className="table-responsive"><table className="table table-hover"><thead><tr><th>Candidate</th><th>Status</th><th>Updated</th><th className="text-end">Likes</th></tr></thead><tbody>{cvs.map((cv) => <tr key={cv.id}><td><Link to={`/cvs/${cv.id}`}>{[cv.user.firstName, cv.user.lastName].filter(Boolean).join(" ") || cv.user.email}</Link></td><td>{cv.status}</td><td>{new Date(cv.updatedAt).toLocaleDateString()}</td><td className="text-end">{cv._count.likes}</td></tr>)}</tbody></table></div>}
    </>}</div>;
}
