import { useCallback, useEffect, useState } from "react";
import { api, json } from "../../api/client";
import { Empty, ErrorAlert, Loading } from "../../components/AsyncState";

const blank = { name: "", description: "", category: "OTHER", type: "STRING", options: "", version: 1 };
const categories = ["CERTIFICATION", "DOMAIN_KNOWLEDGE", "PERSONAL_INFORMATION", "SOFT_SKILLS", "EDUCATION", "EXPERIENCE", "OTHER"];
const types = ["STRING", "TEXT", "IMAGE", "NUMERIC", "DATE", "PERIOD", "BOOLEAN", "SELECT"];
export default function AttributeListPage() {
  const [rows, setRows] = useState(null); const [selected, setSelected] = useState([]); const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [form, setForm] = useState(null); const [error, setError] = useState(null);
  const load = useCallback(() => { api(`/attributes?q=${encodeURIComponent(query)}&category=${category}`).then(setRows).catch(setError); }, [query, category]);
  useEffect(() => { load(); }, [load]);
  const edit = () => { const item = rows.find((x) => x.id === selected[0]); setForm({ ...item, options: item.options.map((x) => x.label).join(", ") }); };
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form, options: form.options.split(",").map((x) => x.trim()).filter(Boolean) }; await api(form.id ? `/attributes/${form.id}` : "/attributes", json(form.id ? "PUT" : "POST", payload)); setForm(null); setSelected([]); load(); } catch (e) { setError(e); } };
  const remove = async () => { if (!confirm("Delete the selected attribute?")) return; try { await api(`/attributes/${selected[0]}`, { method: "DELETE" }); setSelected([]); load(); } catch (e) { setError(e); } };
  return <div className="container py-4"><div className="d-flex justify-content-between"><div><h1 className="h2">Attribute Library</h1><p className="text-secondary">Reusable structured fields shared across every position and profile.</p></div><button className="btn btn-primary align-self-start" onClick={() => setForm(blank)}><i className="bi bi-plus-lg me-2" />New attribute</button></div><ErrorAlert error={error} /><div className="row g-2 mb-3"><div className="col-md-8"><input className="form-control" placeholder="Lookup by name prefix" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="col-md-4"><select className="form-select" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option>{categories.map((x) => <option key={x}>{x}</option>)}</select></div></div>
  {selected.length > 0 && <div className="toolbar alert alert-primary d-flex gap-2"><strong className="me-auto">1 selected</strong><button className="btn btn-sm btn-primary" onClick={edit}>Edit</button><button className="btn btn-sm btn-danger" disabled={rows.find((x) => x.id === selected[0])?.isBuiltIn} onClick={remove}>Delete</button><button className="btn-close" onClick={() => setSelected([])} /></div>}
  {!rows ? <Loading /> : rows.length === 0 ? <Empty>No attributes found.</Empty> : <div className="table-responsive"><table className="table table-hover table-select align-middle"><thead><tr><th></th><th>Name</th><th>Category</th><th>Type</th><th>Description</th><th className="text-end">Used</th></tr></thead><tbody>{rows.map((x) => <tr className={selected.includes(x.id) ? "selected" : ""} key={x.id} onClick={() => setSelected(selected.includes(x.id) ? [] : [x.id])}><td><input type="checkbox" checked={selected.includes(x.id)} readOnly /></td><td className="fw-semibold">{x.name}{x.isBuiltIn && <span className="badge text-bg-info ms-2">Built-in</span>}</td><td>{x.category.replaceAll("_", " ")}</td><td>{x.type}{x.options.length > 0 && <div className="small text-secondary">{x.options.map((o) => o.label).join(", ")}</div>}</td><td>{x.description}</td><td className="text-end">{x.usageCount}</td></tr>)}</tbody></table></div>}
  {form && <div className="modal d-block" tabIndex="-1" style={{ background: "rgba(0,0,0,.45)" }}><div className="modal-dialog modal-lg"><form className="modal-content" onSubmit={save}><div className="modal-header"><h2 className="modal-title h5">{form.id ? "Edit" : "Create"} attribute</h2><button type="button" className="btn-close" onClick={() => setForm(null)} /></div><div className="modal-body"><div className="row g-3"><div className="col-md-6"><label className="form-label">Globally unique name</label><input required className="form-control" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Category</label><select className="form-select" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((x) => <option key={x}>{x}</option>)}</select></div><div className="col-md-3"><label className="form-label">Data type</label><select className="form-select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{types.map((x) => <option key={x}>{x}</option>)}</select></div><div className="col-12"><label className="form-label">Description</label><textarea className="form-control" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>{form.type === "SELECT" && <div className="col-12"><label className="form-label">Dropdown options (comma-separated)</label><input className="form-control" value={form.options} onChange={(e) => setForm({ ...form, options: e.target.value })} /></div>}</div></div><div className="modal-footer"><button type="button" className="btn btn-outline-secondary" onClick={() => setForm(null)}>Cancel</button><button className="btn btn-primary">Save</button></div></form></div></div>}
  </div>;
}
